root: true
env:
  browser: true
  es2022: true
  commonjs: true
  jquery: true
  amd: true
  jest: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'plugin:jest/recommended'
globals:
  process: readonly
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jest
rules:
  indent:
    - error
    - 2
    - FunctionDeclaration:
        parameters: first
      FunctionExpression:
        parameters: first
      CallExpression:
        arguments: first
      ObjectExpression: 1
      ArrayExpression: first
  linebreak-style:
    - error
    - unix
  no-console: off
  no-debugger: warn
  no-unused-vars:
    - warn
    - argsIgnorePattern: "^_"
  camelcase:
    - warn
    - properties: never
      ignoreDestructuring: true
  max-len:
    - warn
    - code: 120
  keyword-spacing: warn
  space-infix-ops: warn
  space-before-function-paren:
    - warn
    - never
  comma-spacing: warn
  brace-style:
    - warn
    - 1tbs
    - allowSingleLine: true
  curly: warn
  operator-linebreak: warn
  block-spacing: warn
  comma-style: error
  dot-location:
    - warn
    - property
  func-call-spacing: error
  key-spacing: warn
  new-cap: warn
  new-parens: warn
  no-extra-parens: warn
  no-floating-decimal: warn
  no-lone-blocks: error
  no-multi-spaces: warn
  no-sequences: error
  no-template-curly-in-string: warn
  no-trailing-spaces: warn
  no-unneeded-ternary: error
  object-curly-newline:
    - warn
    - consistent: true
  rest-spread-spacing: error
  space-before-blocks: warn
  template-curly-spacing: error
  semi:
    - error
    - never
  comma-dangle:
    - error
    - never
  radix:
    - error
    - as-needed
  import/no-unresolved: off
  import/extensions: off
  no-restricted-imports:
    - warn
    - paths:
      - lodash
  import/no-extraneous-dependencies: off
  func-names: off
